//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JizanOMSContext : DbContext
    {
        public JizanOMSContext()
            : base("name=JizanOMSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGateway> tblGateways { get; set; }
        public virtual DbSet<tblRaw> tblRaws { get; set; }
        public virtual DbSet<tblLatest> tblLatests { get; set; }
    
        public virtual int GetLatestMeterReading(string gatewayId)
        {
            var gatewayIdParameter = gatewayId != null ?
                new ObjectParameter("GatewayId", gatewayId) :
                new ObjectParameter("GatewayId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLatestMeterReading", gatewayIdParameter);
        }
    }
}
