//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOms
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLatest
    {
        public System.Guid Id { get; set; }
        public string MeterAddress { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public string RawTelegram { get; set; }
        public string GatewayId { get; set; }
    }
}
